apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwNTEyMy5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiVUhWeWJtRk9ZWFJvT2xadmIyNXVZVUF3T1E9PSIKCQl9Cgl9Cn0= 
type: kubernetes.io/dockerconfigjson